"""Email digest builder and sender."""
from __future__ import annotations

import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from jinja2 import Template


HTML_TEMPLATE = Template("""<!doctype html>
<html><body style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 720px; margin: 0 auto; color: #222;">
<h2>CT Flip Watch — {{ today }}</h2>
<p style="color:#666;">Top {{ deals|length }} ranked deals from Greenwich, Stamford, Darien, New Canaan, Norwalk.
Scanned {{ total_listings }} active listings. Higher score = stronger flip candidate.</p>

{% for d in deals %}
<div style="border:1px solid #ddd; border-radius:8px; padding:16px; margin-bottom:18px;">
  <div style="display:flex; justify-content:space-between; align-items:center;">
    <h3 style="margin:0;">
      <a href="{{ d.url }}" style="color:#0a58ca; text-decoration:none;">{{ d.address }}</a>
    </h3>
    <span style="background:{{ d.score_color }}; color:white; padding:4px 10px; border-radius:12px; font-weight:bold;">
      {{ d.score }}
    </span>
  </div>
  <p style="margin:6px 0; color:#444;">
    <strong>${{ "{:,}".format(d.price) }}</strong>
    &middot; {{ d.beds }}bd / {{ d.baths }}ba
    &middot; {{ "{:,}".format(d.sqft) }} sqft
    &middot; built {{ d.year_built or "?" }}
    &middot; {{ d.dom }} days on market
  </p>

  {% if d.image %}<img src="{{ d.image }}" style="max-width:100%; border-radius:6px; margin:8px 0;" />{% endif %}

  <table style="width:100%; font-size:14px; border-collapse:collapse; margin-top:8px;">
    <tr><td style="padding:4px 8px; color:#666;">ARV estimate</td><td>{{ d.arv }}</td></tr>
    <tr><td style="padding:4px 8px; color:#666;">Rehab estimate</td><td>{{ d.rehab }}</td></tr>
    <tr><td style="padding:4px 8px; color:#666;">Condition</td><td>{{ d.condition }}</td></tr>
    <tr><td style="padding:4px 8px; color:#666;">Max bid (luxury formula)</td><td>{{ d.max_bid }}</td></tr>
    <tr><td style="padding:4px 8px; color:#666;">Potential profit</td><td><strong>{{ d.profit }}</strong></td></tr>
    <tr><td style="padding:4px 8px; color:#666;">$/sqft vs town median</td><td>{{ d.ppsqft }}</td></tr>
    <tr><td style="padding:4px 8px; color:#666;">Distressed signals</td><td>{{ d.signals or "—" }}</td></tr>
    <tr><td style="padding:4px 8px; color:#666;">Price drops</td><td>{{ d.drops }}</td></tr>
  </table>

  {% if d.rehab_notes %}
  <p style="margin-top:10px; padding:10px; background:#f6f8fa; border-radius:6px; font-size:13px;">
    <strong>AI rehab notes:</strong> {{ d.rehab_notes }}
  </p>
  {% endif %}
</div>
{% endfor %}

<p style="color:#888; font-size:12px; margin-top:30px;">
  Generated by Skynet Flip Watch. ARV uses active comps (directional only — true flip math needs SOLD comps).
  Rehab estimated by Claude vision from listing photos. Verify everything before bidding.
</p>
</body></html>""")


def _money(n: int | float | None) -> str:
    if n is None:
        return "—"
    return f"${int(n):,}"


def _color_for(score: float) -> str:
    if score >= 75:
        return "#198754"
    if score >= 60:
        return "#fd7e14"
    return "#6c757d"


def build_html(scored: list[dict[str, Any]], total_listings: int) -> str:
    deals: list[dict[str, Any]] = []
    for item in scored:
        listing = item["listing"]
        b = item["breakdown"]
        rehab = item["rehab"]
        zpid = listing.get("zpid")

        ppsqft_str = "—"
        if "listing_ppsqft" in b and "town_median_ppsqft" in b:
            delta_pct = (b["town_median_ppsqft"] - b["listing_ppsqft"]) / b["town_median_ppsqft"] * 100
            ppsqft_str = f"${b['listing_ppsqft']:.0f} vs ${b['town_median_ppsqft']:.0f} ({delta_pct:+.1f}%)"

        deals.append({
            "url": f"https://www.zillow.com/homedetails/{zpid}_zpid/",
            "address": listing.get("address") or "Address unavailable",
            "score": b["total_score"],
            "score_color": _color_for(b["total_score"]),
            "price": listing.get("price") or 0,
            "beds": listing.get("bedrooms") or "?",
            "baths": listing.get("bathrooms") or "?",
            "sqft": listing.get("livingArea") or 0,
            "year_built": listing.get("yearBuilt"),
            "dom": b.get("days_on_market", 0),
            "image": (listing.get("imgSrc") or ""),
            "arv": _money(b.get("arv_estimate")),
            "rehab": _money(rehab["total"]) + f" (${rehab['per_sqft']:.0f}/sqft)",
            "condition": rehab["condition"],
            "max_bid": _money(b.get("max_bid")),
            "profit": _money(b.get("potential_profit")),
            "ppsqft": ppsqft_str,
            "signals": ", ".join(b.get("distressed_signals", [])),
            "drops": f"{b.get('price_drop_count', 0)} drops, {b.get('price_drop_pct', 0)*100:.1f}% off initial",
            "rehab_notes": rehab.get("notes", ""),
        })

    return HTML_TEMPLATE.render(
        today=date.today().isoformat(),
        deals=deals,
        total_listings=total_listings,
    )


def send_email(html: str, subject: str) -> None:
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = os.environ["DIGEST_FROM"]
    msg["To"] = os.environ["DIGEST_TO"]
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(os.environ["SMTP_HOST"], int(os.environ["SMTP_PORT"])) as s:
        s.starttls()
        s.login(os.environ["SMTP_USER"], os.environ["SMTP_PASSWORD"])
        s.send_message(msg)
